In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
#read the file and save the dataframe to the variable called alldata
filepath=r"C:\Users\Egecan\Desktop\Data Incubator2\NYC_Wi-Fi_Hotspot_Locations.csv"
alldata=pd.read_csv(filepath)

In [3]:
alldata

,OBJECTID,Borough,Type,Provider,Name,Location,Latitude,Longitude,X,Y,...,Neighborhood Tabulation Area (NTA),Council Distrcit,Postcode,BoroCD,Census Tract,BCTCB2010,BIN,BBL,DOITT_ID,"Location (Lat, Long)"
0,10604,4,Limited Free,SPECTRUM,Baisley Pond Park,Park Perimeter,40.674860,-73.784120,1.044132e+06,185219.892077,...,Springfield Gardens North,28,11434,412,294,294,0,0,1408,"(40.6748599999, -73.7841200005)"
1,10555,4,Limited Free,SPECTRUM,Kissena Park,Park Perimeter,40.747560,-73.818150,1.034638e+06,211685.217755,...,Flushing,20,11355,407,845,845,0,0,1359,"(40.7475599996, -73.8181499997)"
2,12370,3,Free,Transit Wireless,Grand St (L),Grand St (L),40.711926,-73.940670,1.000698e+06,198655.908840,...,East Williamsburg,34,11206,301,495,495,0,0,1699,"(40.7119259997, -73.9406699994)"
3,9893,3,Free,Downtown Brooklyn,NaN,125 Court St.,40.689985,-73.991995,9.864700e+05,190656.680416,...,Brooklyn Heights-Cobble Hill,33,11201,302,9,9,3388736,3002777501,298,"(40.6899850001, -73.9919950004)"
4,10169,1,Free,Transit Wireless,Lexington Av-63 St (F),Lexington Av-63 St (F),40.764630,-73.966115,9.936366e+05,217853.888161,...,Upper East Side-Carnegie Hill,4,10065,108,120,120,0,0,599,"(40.7646300002, -73.9661150001)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3314,10872,3,Limited Free,SPECTRUM,Carroll Park,Court off Smith St between Carrol St and 1st P...,40.680630,-73.995382,9.855309e+05,187248.314202,...,Carroll Gardens-Columbia Street-Red Hook,39,11231,306,77,77,3007547,3004490015,1338,"(40.6806299998, -73.9953819995)"
3315,12026,2,Free,LinkNYC - Citybridge,bx-01-138789,312 WILLIS AVENUE,40.810896,-73.921434,1.005999e+06,234718.294065,...,Mott Haven-Port Morris,8,10454,201,39,39,2000335,2022850010,4113,"(40.8108964904, -73.9214341701)"
3316,12063,3,Free,LinkNYC - Citybridge,bk-01-143982,32 GRAHAM AVENUE,40.701930,-73.942239,1.000265e+06,195013.901033,...,East Williamsburg,34,11206,301,491,491,3071609,3031200000,3018,"(40.7019303441, -73.9422392381)"
3317,12066,3,Free,LinkNYC - Citybridge,bk-17-126527,1339 FLATBUSH AVENUE,40.638560,-73.953603,9.971268e+05,171924.271359,...,Erasmus,45,11226,317,790,790,3120360,3052110060,3021,"(40.6385596088, -73.9536032378)"
3318,12083,3,Free,LinkNYC - Citybridge,bk-02-108355,402 Atlantic Avenue,40.686812,-73.984970,9.884185e+05,189500.763109,...,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,33,11217,302,41,41,3255607,3001837500,3038,"(40.6868115694, -73.9849696135)"

In [4]:
providers=alldata["Provider"]
print("Number of unique providers are {}.".format(len(set(providers))))

Number of unique providers are 17.

In [5]:
locations=alldata["Location"]

In [6]:
locations

0                                          Park Perimeter
1                                          Park Perimeter
2                                            Grand St (L)
3                                           125 Court St.
4                                  Lexington Av-63 St (F)
                              ...
3314    Court off Smith St between Carrol St and 1st P...
3315                                    312 WILLIS AVENUE
3316                                     32 GRAHAM AVENUE
3317                                 1339 FLATBUSH AVENUE
3318                                  402 Atlantic Avenue
Name: Location, Length: 3319, dtype: object

In [7]:
counter=0
for i in range(len(locations)):
    if "Park" in locations[i]:
        counter+=1
print("Fraction of WiFi hotspots that are in parks is: {:.3f}.".format(counter/(len(locations))))

Fraction of WiFi hotspots that are in parks is: 0.036.

In [8]:
alldata[alldata["Name"].str.contains("Park",na=False)]

,OBJECTID,Borough,Type,Provider,Name,Location,Latitude,Longitude,X,Y,...,Neighborhood Tabulation Area (NTA),Council Distrcit,Postcode,BoroCD,Census Tract,BCTCB2010,BIN,BBL,DOITT_ID,"Location (Lat, Long)"
0,10604,4,Limited Free,SPECTRUM,Baisley Pond Park,Park Perimeter,40.674860,-73.784120,1.044132e+06,185219.892077,...,Springfield Gardens North,28,11434,412,294,294,0,0,1408,"(40.6748599999, -73.7841200005)"
1,10555,4,Limited Free,SPECTRUM,Kissena Park,Park Perimeter,40.747560,-73.818150,1.034638e+06,211685.217755,...,Flushing,20,11355,407,845,845,0,0,1359,"(40.7475599996, -73.8181499997)"
5,10880,4,Limited Free,SPECTRUM,Kissena Park,Park Perimeter,40.742430,-73.811510,1.036481e+06,209820.088612,...,Queensboro Hill,20,11355,407,1215,1215,0,0,1347,"(40.7424300003, -73.8115100003)"
10,11726,2,Limited Free,ALTICEUSA,Crotona Park,CROTONA PARK C/O EAST 173RD ST AND FULTON AVE,40.840664,-73.898372,1.012370e+06,245570.243161,...,Claremont-Bathgate,16,10457,203,167,167,0,0,1285,"(40.8406639999, -73.8983720002)"
45,10978,1,Free,AT&T,Marcus Garvey Park,Amphitheater,40.804800,-73.944300,9.996703e+05,232492.276207,...,East Harlem North,9,10027,111,198,198,0,1017190001,11,"(40.8048000002, -73.9443)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,11709,2,Limited Free,ALTICEUSA,Crotona Park,Crotona Park-CROTONA PARK SOUTH 1/P/E/O CROTON...,40.834480,-73.897582,1.012591e+06,243317.437955,...,Morrisania-Melrose,16,10456,203,151,151,0,0,1266,"(40.8344799999, -73.8975819996)"
3304,10747,2,Limited Free,ALTICEUSA,Ferry Point Park,BALCOM AV 5/P/E/O SCHLEY AV,40.820619,-73.825839,1.032454e+06,238298.719975,...,Schuylerville-Throgs Neck-Edgewater Park,13,10465,210,110,110,0,0,1297,"(40.8206190002, -73.8258389999)"
3305,10752,2,Limited Free,ALTICEUSA,Ferry Point Park,C/O SCHLEY AV /BRUSH AV,40.816412,-73.833998,1.030199e+06,236761.576067,...,Schuylerville-Throgs Neck-Edgewater Park,13,10465,210,110,110,0,2056220001,1302,"(40.8164119996, -73.8339979997)"
3306,10757,3,Limited Free,ALTICEUSA,Gravesend Park,EASEMENT 56TH ST 5 P/S/18TH AV,40.623831,-73.983592,9.888048e+05,166555.261100,...,Borough Park,44,11204,312,468,468,0,3054940008,1307,"(40.6238310001, -73.9835919996)"
3314,10872,3,Limited Free,SPECTRUM,Carroll Park,Court off Smith St between Carrol St and 1st P...,40.680630,-73.995382,9.855309e+05,187248.314202,...,Carroll Gardens-Columbia Street-Red Hook,39,11231,306,77,77,3007547,3004490015,1338,"(40.6806299998, -73.9953819995)"

In [9]:
(len(alldata[alldata["Name"].str.contains("Park",na=False)])+len(alldata[alldata["Name"].str.contains("PARK",na=False)]))

400

In [10]:
(len(alldata[alldata["Name"].str.contains("Park",na=False)])+len(alldata[alldata["Name"].str.contains("PARK",na=False)]))/len(alldata)

0.12051822838204278

In [11]:
400/3319

0.12051822838204278

In [12]:
len(alldata)

3319

In [13]:
provider_grouped=alldata.groupby("Provider")

In [14]:
provider_grouped.size().sort_values(ascending=False)

Provider
LinkNYC - Citybridge       1868
SPECTRUM                    343
Transit Wireless            276
ALTICEUSA                   237
Harlem                      101
Downtown Brooklyn           100
NYPL                         90
QPL                          65
BPL                          59
Manhattan Down Alliance      36
Fiberless                    30
Chelsea                      30
NYCHA                        28
AT&T                         27
Spot On Networks             16
City Tech                    11
Partner                       2
dtype: int64

In [15]:
alldata.loc[(alldata["Borough"]==2) & (alldata["Provider"])=="SPECTRUM"]

Empty DataFrame
Columns: [OBJECTID, Borough, Type, Provider, Name, Location, Latitude, Longitude, X, Y, Location_T, Remarks, City, SSID, SourceID, Activated, BoroCode, Borough Name, Neighborhood Tabulation Area Code (NTACODE), Neighborhood Tabulation Area (NTA), Council Distrcit, Postcode, BoroCD, Census Tract, BCTCB2010, BIN, BBL, DOITT_ID, Location (Lat, Long)]
Index: []

[0 rows x 29 columns]

In [16]:
np.sort(provider_grouped.size())

array([   2,   11,   16,   27,   28,   30,   30,   36,   59,   65,   90,
        100,  101,  237,  276,  343, 1868], dtype=int64)

In [17]:
bronx=alldata[alldata["Borough"]==2]

In [18]:
bronx.groupby("Provider").size().sort_values(ascending=False)

Provider
LinkNYC - Citybridge    137
ALTICEUSA               120
NYPL                     35
Transit Wireless         21
AT&T                      3
dtype: int64

In [19]:
nolib=alldata[alldata["Location_T"]!="Library"]
nolib

,OBJECTID,Borough,Type,Provider,Name,Location,Latitude,Longitude,X,Y,...,Neighborhood Tabulation Area (NTA),Council Distrcit,Postcode,BoroCD,Census Tract,BCTCB2010,BIN,BBL,DOITT_ID,"Location (Lat, Long)"
0,10604,4,Limited Free,SPECTRUM,Baisley Pond Park,Park Perimeter,40.674860,-73.784120,1.044132e+06,185219.892077,...,Springfield Gardens North,28,11434,412,294,294,0,0,1408,"(40.6748599999, -73.7841200005)"
1,10555,4,Limited Free,SPECTRUM,Kissena Park,Park Perimeter,40.747560,-73.818150,1.034638e+06,211685.217755,...,Flushing,20,11355,407,845,845,0,0,1359,"(40.7475599996, -73.8181499997)"
2,12370,3,Free,Transit Wireless,Grand St (L),Grand St (L),40.711926,-73.940670,1.000698e+06,198655.908840,...,East Williamsburg,34,11206,301,495,495,0,0,1699,"(40.7119259997, -73.9406699994)"
3,9893,3,Free,Downtown Brooklyn,NaN,125 Court St.,40.689985,-73.991995,9.864700e+05,190656.680416,...,Brooklyn Heights-Cobble Hill,33,11201,302,9,9,3388736,3002777501,298,"(40.6899850001, -73.9919950004)"
4,10169,1,Free,Transit Wireless,Lexington Av-63 St (F),Lexington Av-63 St (F),40.764630,-73.966115,9.936366e+05,217853.888161,...,Upper East Side-Carnegie Hill,4,10065,108,120,120,0,0,599,"(40.7646300002, -73.9661150001)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3314,10872,3,Limited Free,SPECTRUM,Carroll Park,Court off Smith St between Carrol St and 1st P...,40.680630,-73.995382,9.855309e+05,187248.314202,...,Carroll Gardens-Columbia Street-Red Hook,39,11231,306,77,77,3007547,3004490015,1338,"(40.6806299998, -73.9953819995)"
3315,12026,2,Free,LinkNYC - Citybridge,bx-01-138789,312 WILLIS AVENUE,40.810896,-73.921434,1.005999e+06,234718.294065,...,Mott Haven-Port Morris,8,10454,201,39,39,2000335,2022850010,4113,"(40.8108964904, -73.9214341701)"
3316,12063,3,Free,LinkNYC - Citybridge,bk-01-143982,32 GRAHAM AVENUE,40.701930,-73.942239,1.000265e+06,195013.901033,...,East Williamsburg,34,11206,301,491,491,3071609,3031200000,3018,"(40.7019303441, -73.9422392381)"
3317,12066,3,Free,LinkNYC - Citybridge,bk-17-126527,1339 FLATBUSH AVENUE,40.638560,-73.953603,9.971268e+05,171924.271359,...,Erasmus,45,11226,317,790,790,3120360,3052110060,3021,"(40.6385596088, -73.9536032378)"
3318,12083,3,Free,LinkNYC - Citybridge,bk-02-108355,402 Atlantic Avenue,40.686812,-73.984970,9.884185e+05,189500.763109,...,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,33,11217,302,41,41,3255607,3001837500,3038,"(40.6868115694, -73.9849696135)"

In [20]:
len(nolib[nolib["Type"]=="Free"])/len(nolib)

0.8122383252818035

In [21]:
NTA=alldata.groupby("Neighborhood Tabulation Area Code (NTACODE)").size().sort_values(ascending=False)

In [22]:
NTA=NTA[NTA>29.0]
NTA

Neighborhood Tabulation Area Code (NTACODE)
MN17    160
MN13    156
MN12    143
BK38    125
MN19    111
MN03    101
MN20     82
MN11     69
MN34     65
MN04     63
MN22     58
MN24     58
MN40     54
QN70     54
MN14     52
MN25     52
MN31     52
QN31     52
MN21     51
MN23     49
MN36     48
MN15     46
BK68     46
MN99     44
BK61     44
MN09     42
BX39     41
BK73     40
BX63     40
QN29     39
BK37     35
BX99     34
BK21     32
QN17     30
dtype: int64

In [23]:
filepath=r"C:\Users\Egecan\Desktop\Data Incubator2\Census_Demographics_at_the_Neighborhood_Tabulation_Area__NTA__level.csv"
population=pd.read_csv(filepath)

In [24]:
indexlist=list(NTA.index)

In [25]:
NTA=NTA.astype(float)

In [26]:
population[population["Geographic Area - Neighborhood Tabulation Area (NTA)* Code"]=='QN17']

,Geographic Area - Borough,Geographic Area - 2010 Census FIPS County Code,Geographic Area - Neighborhood Tabulation Area (NTA)* Code,Geographic Area - Neighborhood Tabulation Area (NTA)* Name,Total Population 2000 Number,Total Population 2010 Number,Total Population Change 2000-2010 Number,Total Population Change 2000-2010 Percent
128,Queens,81.0,QN17,Forest Hills,85046.0,83728.0,-1318.0,-1.5

In [27]:

for nta in indexlist:
    NTA[nta]=NTA[nta]/float(population[population["Geographic Area - Neighborhood Tabulation Area (NTA)* Code"]==nta]["Total Population 2010 Number"])

In [28]:
NTA

Neighborhood Tabulation Area Code (NTACODE)
MN17    0.005589
MN13    0.002224
MN12    0.001080
BK38    0.003624
MN19    0.002167
MN03    0.001342
MN20    0.001616
MN11    0.001590
MN34    0.001120
MN04    0.001298
MN22    0.001314
MN24    0.001357
MN40    0.000882
QN70    0.000685
MN14    0.000846
MN25    0.001310
MN31    0.000644
QN31    0.000822
MN21    0.001822
MN23    0.000733
MN36    0.000568
MN15    0.001003
BK68    0.001764
MN99    0.023797
BK61    0.000426
MN09    0.000751
BX39    0.000782
BK73    0.000874
BX63    0.001018
QN29    0.000441
BK37    0.000517
BX99    0.017838
BK21    0.001001
QN17    0.000358
dtype: float64

In [35]:
min(NTA)

0.00035830307662908467

In [37]:
NTA.quantile(0.250)

0.0007587762446786567

In [38]:
NTA.quantile(0.750)

0.0016096349044708714

In [31]:
NTA.quantile(.75)-NTA.quantile(.25)

0.0008508586597922147